# Generated by Django 4.0.2 on 2022-02-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addlease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wcountry', models.CharField(max_length=30)),
                ('Dcountry', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ldetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=20)),
                ('Lname', models.CharField(max_length=20)),
                ('Email_ID', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=13)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=40)),
                ('Status', models.BooleanField(default=False)),
                ('File', models.FileField(upload_to='')),
            ],
        ),
    ]
