# Generated by Django 4.0.2 on 2022-03-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqpp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fromdate', models.DateField()),
                ('Todate', models.DateField()),
                ('Sizecontain', models.CharField(max_length=20)),
                ('Ratecontain', models.CharField(max_length=20)),
                ('Containername', models.CharField(max_length=20)),
                ('Customersname', models.CharField(max_length=20)),
            ],
        ),
    ]
